name: Test
on: push
jobs:
  Lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cmd: npm run lint
  Build-test:
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: http://localhost:3000
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x # will run `npm install` command
      - run: |
        npm install
        npm run build
      - run: npm test
        env:
          CI: true
