name: Test
on: push
jobs:
  Lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: npm run lint # will run `yarn build` command
  Build-test:
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: http://localhost:3000
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: npm install # will run `npm install` command
      - name: Run build check
        run: npm run build
      - run: npm test
        env:
          CI: true
